### ISSUE TITLE
Renovate bot just blundered react hooks

### ISSUE THREAD

**Issue by paean99** [benawad/codeponder#112]
The latest commit https://github.com/benawad/codeponder/commit/d474ee7a6865f0cfcf276d164ab4d9acfdf1777e
just did 16.7.0-alpha.2 => 16.7.0. So no more react hooks :(

I think you can configure renovate bot for it to not touch the react package with packageRules.
You could use the https://renovatebot.com/docs/configuration-options/#allowedversions for example

**Comment by benawad** [comment]
thanks for the heads up, I ignored `react` and `react-dom`
