### ISSUE TITLE
Unable to connect to localhost:3000 after fetching master

### ISSUE THREAD

**Issue by onemen** [benawad/codeponder#230]
Unable to connect to localhost:3000 after fetching [master](https://github.com/benawad/codeponder/commit/386fb4dba925bc2a3a963df50faae947e5531890)

**Comment by benawad** [comment]
What error do you get?

**Comment by benawad** [comment]
On the server you need to add stuff to your .env

**Comment by onemen** [comment]
i'v added with value SESSION_SECRET, DB_USER, DB_PASS.
any spacial value? 
i'v use the value from ormconfig.json to DB_USER, DB_PASS and the value that was in the code for SESSION_SECRET.

I keep getting 'Restarting' toast message until i see the message from the browser

![toast](https://user-images.githubusercontent.com/3650909/51806979-80e70b00-2289-11e9-938b-2a5819ea252b.png)
![unable_to_connect](https://user-images.githubusercontent.com/3650909/51806980-817fa180-2289-11e9-9339-23be7f206d04.png)

**Comment by benawad** [comment]
Those values are correct for SESSION_SECRET, DB_USER, DB_PASS.

We can keep ts-node at v7 for now then. Does ts-node-dev not work on windows?

**Comment by onemen** [comment]
ts-node-dev use ts-node v8

**Comment by onemen** [comment]
I was able to use ts-node version 8.0.2 + nodemon with this change on nodemon.json

```diff
-  "ts": "ts-node --typeCheck --project tsconfig.server.json"
+  "ts": "ts-node --type-check --project tsconfig.server.json"
```
but it doesn't work when using ts-node-dev, it keep compiling packages\web every 20-30 sec

**Comment by benawad** [comment]
ok we can just keep nodemon then

**Comment by onemen** [comment]
I am able to use ts-node-dev after changing these lines in packages\web\package.json 
```diff
-    "dev": "ts-node-dev --respawn --project tsconfig.server.json server/index.ts",
+    "dev": "ts-node-dev --respawn --ignore-watch .next --project tsconfig.server.json server\index.ts",
```

**Comment by benawad** [comment]
ok I'll add that

**Comment by onemen** [comment]
...and remove nodemon
