### ISSUE TITLE
Windows compatibility

### ISSUE THREAD

**Issue by itstimetogoleft** [benawad/codeponder#7]
I wanted to leave an issue open for everyone who is trying to run codeponder on Windows. There is two steps to follow:

First, go to /packages/server/package.json and remove the `NODE_ENV` variable from the start script. Tt should stay:

`"start": "nodemon --exec ts-node src/index.ts",`

as far as i know, Windows does not allow you to set env variables that way, we could use the cross-env package or set the variable through powershell or cmd; but instead since the project is using the dotenv-safe package we can leverage that and add the variable on the .env file.

then if we try to run the web server we may run into the following problem:

`starting 'ts-node --compilerOptions '{"module":"commonjs"}' server/index.ts'
undefined:1'{module:commonjs}'
^
SyntaxError: Unexpected token ' in JSON at position 0`

in order to make it work we need to go to to `packages/web/nodemon.json` and replace:

`"ts": "ts-node --typeCheck --compilerOptions '{\"module\":\"commonjs\"}'"`

for:

 `"ts": "ts-node --compilerOptions {\"\"\"module\"\"\":\"\"\"commonjs\"\"\"}"`

That's all, assuming you have everything (redis, postgres) set up correctly.

I've not tested if this doesn't break compatibility for mac and linux, if someone can confirm i can go ahead and submit a pull request.

**Comment by benawad** [comment]
I think we can remove the compilerOptions all together because we created an extra tsconfig.

**Comment by benawad** [comment]
I think this commit may fix things? https://github.com/benawad/codeponder/commit/a20bec2ea925aa5de2cb4c406dbf7f2477be5ab2
