### ISSUE TITLE
eslint-plugin-react-hooks

### ISSUE THREAD

**Issue by paean99** [benawad/codeponder#99]
I think that eslint-plugin-react-hooks is not used yet in this project. Since codeponder is using react hooks, I would be interesting to add them as they are part of the hooks proposal.

https://www.npmjs.com/package/eslint-plugin-react-hooks

**Comment by benawad** [comment]
Is there a tslint version of this?

**Comment by paean99** [comment]
There is a temporary solution from tslint-react which is a sub package of tslint and from the same developers at https://github.com/palantir/tslint-react/issues/186#issuecomment-448983211

I think the solution does need tslint-react but i haven't tested it yet.

**Comment by benawad** [comment]
rather than setting up eslint for typescript, I think I'll just wait until tslint supports it

**Comment by Gelio** [comment]
@benawad Take a look at a TSLint rule that detects possible misuses of hooks: https://github.com/Gelio/tslint-react-hooks

Disclaimer: I am the author. I noticed this issue referenced in another repo, so I thought I would let you know that you may try using that rule 🙂 I am looking for feedback 😄
